# This GitHub Action CI would support Apple silicon series in the future.
# Please feel free to pull request if this issue has been solved:
# https://github.com/github/roadmap/issues/528
# 
# We templarly use the x86_64 version of the GitHub Action CI.

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BUILD_DEBUG_DIR: build-debug
  BUILD_RELEASE_DIR: build-release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-debug:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: CMake generate Debug version
        run: cmake -B ${{ env.BUILD_DEBUG_DIR }} -DCMAKE_BUILD_TYPE=Debug

      - name: CMake build Debug version
        run: cmake --build ${{ env.BUILD_DEBUG_DIR }} --config Debug
    
      - name: CTest
        run: cmake --build ${{ env.BUILD_DEBUG_DIR }} --config Debug --target test

  ci-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: CMake generate Release version
        run: cmake -B ${{ env.BUILD_RELEASE_DIR }} -DCMAKE_BUILD_TYPE=Release

      - name: CMake build Release version
        run: cmake --build ${{ env.BUILD_RELEASE_DIR }} --config Release
      
      - name: CTest
        run: cmake --build ${{ env.BUILD_RELEASE_DIR }} --config Release --target test
